/**
 * Imobiliária Meridional - Dataset Oficial de Imóveis e Lançamentos
 * Com imagens originais e acervo real de Uberaba/MG
 */

const PROPERTIES_DATA = [
  // --- VENDA: DESTAQUES & CONDOMÍNIOS ---
  {
    id: "3277",
    code: "ME-3277",
    title: "Damha II Loteamento Fechado",
    type: "casa",
    category: "condominio",
    purpose: "venda",
    price: 3650000,
    rentalPrice: 28000,
    condoFee: 980,
    iptu: 3400,
    neighborhood: "Damha II",
    city: "Uberaba",
    state: "MG",
    address: "Condomínio Residencial Damha II",
    area: 480,
    builtArea: 420,
    bedrooms: 4,
    suites: 4,
    bathrooms: 6,
    parkingSpots: 4,
    featured: true,
    isSale: true,
    isRent: false,
    badge: "Exclusividade Damha",
    description: "Espetacular residência no Damha II. Acabamento primoroso, 4 suítes completas com armários, sala ampla para 3 ambientes, lavabo, varanda gourmet integrada à piscina aquecida com hidromassagem e cascata, energia solar e 4 vagas de garagem.",
    features: ["Piscina Aquecida", "Espaço Gourmet", "Energia Solar", "4 Suítes com Closet", "Segurança 24h Damha", "Quadra de Tênis"],
    images: [
      "https://meridional.imb.br/resize.php?img=3277/001.jpeg&width=600&height=400",
      "https://meridional.imb.br/resize.php?img=3277/001.jpeg&width=800&height=600",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3234",
    code: "ME-3234",
    title: "Condomínio Fechado Flamboyant",
    type: "casa",
    category: "condominio",
    purpose: "venda",
    price: 2100000,
    rentalPrice: 12000,
    condoFee: 750,
    iptu: 2100,
    neighborhood: "Flamboyant",
    city: "Uberaba",
    state: "MG",
    address: "Residencial Flamboyant II",
    area: 390,
    builtArea: 310,
    bedrooms: 3,
    suites: 3,
    bathrooms: 5,
    parkingSpots: 4,
    featured: true,
    isSale: true,
    isRent: false,
    badge: "Destaque Flamboyant",
    description: "Casa contemporânea em condomínio fechado. 3 suítes amplas com ar condicionado, sala com pé-direito duplo, cozinha gourmet planejada, área de lazer com piscina e churrasqueira, acabamentos nobres.",
    features: ["Piscina com Cascata", "Área Gourmet", "Móveis Planejados", "Segurança 24h", "Garagem para 4 Carros"],
    images: [
      "https://meridional.imb.br/resize.php?img=3234/1(3).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3273",
    code: "ME-3273",
    title: "Casa Jardim Nenê Gomes",
    type: "casa",
    category: "casa",
    purpose: "venda",
    price: 890000,
    rentalPrice: 4200,
    condoFee: 0,
    iptu: 1100,
    neighborhood: "Jardim Nenê Gomes",
    city: "Uberaba",
    state: "MG",
    address: "Jardim Nenê Gomes",
    area: 280,
    builtArea: 215,
    bedrooms: 3,
    suites: 2,
    bathrooms: 4,
    parkingSpots: 2,
    featured: true,
    isSale: true,
    isRent: false,
    badge: "Venda Destaque",
    description: "Casa nova com acabamento diferenciado. 3 dormitórios sendo 2 suítes, sala em 2 ambientes, cozinha gourmet integrada com churrasqueira, quintal espaçoso e garagem coberta.",
    features: ["Porcelanato Polido", "Espaço Gourmet", "Iluminação LED", "Portão Eletrônico"],
    images: [
      "https://meridional.imb.br/resize.php?img=3273/1(1).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3334",
    code: "ME-3334",
    title: "Apartamento Centro ME 4283",
    type: "apartamento",
    category: "apartamento",
    purpose: "venda",
    price: 360000,
    rentalPrice: 2200,
    condoFee: 420,
    iptu: 750,
    neighborhood: "Centro",
    city: "Uberaba",
    state: "MG",
    address: "Região Central de Uberaba",
    area: 94,
    builtArea: 94,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 1,
    featured: true,
    isSale: true,
    isRent: false,
    badge: "Oportunidade Centro",
    description: "Apartamento reformado no Centro de Uberaba. 2 dormitórios (1 suíte) com armários, sala em L com sacada e vista panorâmica, cozinha com armários e bancada em granito.",
    features: ["Centro da Cidade", "Sacada Panorâmica", "Armários Embutidos", "Elevador", "Portaria"],
    images: [
      "https://meridional.imb.br/resize.php?img=3334/1(16).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3226",
    code: "ME-3226",
    title: "Residencial Turim ME 4206",
    type: "apartamento",
    category: "apartamento",
    purpose: "venda",
    price: 155000,
    rentalPrice: 1100,
    condoFee: 220,
    iptu: 350,
    neighborhood: "Parque das Américas",
    city: "Uberaba",
    state: "MG",
    address: "Residencial Turim",
    area: 52,
    builtArea: 52,
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    parkingSpots: 1,
    featured: true,
    isSale: true,
    isRent: false,
    badge: "Minha Casa Minha Vida",
    description: "Apartamento ideal para investimento ou moradia. 2 quartos, sala, cozinha americana, banheiro social, garagem e condomínio com área de lazer.",
    features: ["Financiamento Caixa", "Condomínio Fechado", "Área de Lazer", "Portaria 24h"],
    images: [
      "https://meridional.imb.br/resize.php?img=3226/1(7).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "2302",
    code: "ME-2302",
    title: "Damha III Uberaba ME 2646",
    type: "terreno",
    category: "condominio",
    purpose: "venda",
    price: 490000,
    rentalPrice: 0,
    condoFee: 650,
    iptu: 1200,
    neighborhood: "Damha III",
    city: "Uberaba",
    state: "MG",
    address: "Condomínio Damha III",
    area: 450,
    builtArea: 0,
    bedrooms: 0,
    suites: 0,
    bathrooms: 0,
    parkingSpots: 0,
    featured: true,
    isSale: true,
    isRent: false,
    badge: "Lote Nobre Damha",
    description: "Excelente terreno plano no Damha III, próximo à portaria e complexo esportivo. Pronto para construir a residência dos seus sonhos.",
    features: ["Topografia Plana", "Segurança Máxima", "Clube com Lago", "Pronto para Construir"],
    images: [
      "https://meridional.imb.br/resize.php?img=2302/01.jpg&width=600&height=400",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80"
    ]
  },

  // --- LOCAÇÃO: DESTAQUES ---
  {
    id: "3318",
    code: "ME-3318",
    title: "Edifício Évros Alto Padrão",
    type: "apartamento",
    category: "apartamento",
    purpose: "aluguel",
    price: 980000,
    rentalPrice: 4500,
    condoFee: 850,
    iptu: 1400,
    neighborhood: "Mercês",
    city: "Uberaba",
    state: "MG",
    address: "Bairro Mercês, Próximo Praça Dom Eduardo",
    area: 168,
    builtArea: 168,
    bedrooms: 3,
    suites: 3,
    bathrooms: 5,
    parkingSpots: 2,
    featured: true,
    isSale: false,
    isRent: true,
    badge: "Locação Mercês",
    description: "Apartamento nobre no Edifício Évros. 3 suítes climatizadas, varanda gourmet com churrasqueira, sala para 3 ambientes, lavabo, lazer completo no prédio e 2 vagas paralelas.",
    features: ["3 Suítes", "Varanda Gourmet", "Piscina e Academia", "Portaria 24h", "Bairro Nobre Mercês"],
    images: [
      "https://meridional.imb.br/resize.php?img=3318/1(32).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3317",
    code: "ME-3317",
    title: "Casa Residencial Damha Locação",
    type: "casa",
    category: "condominio",
    purpose: "aluguel",
    price: 2400000,
    rentalPrice: 8500,
    condoFee: 950,
    iptu: 2200,
    neighborhood: "Damha I",
    city: "Uberaba",
    state: "MG",
    address: "Condomínio Residencial Damha I",
    area: 420,
    builtArea: 350,
    bedrooms: 4,
    suites: 4,
    bathrooms: 5,
    parkingSpots: 4,
    featured: true,
    isSale: false,
    isRent: true,
    badge: "Locação Damha",
    description: "Excelente residência disponível para locação no Damha I. 4 suítes, sala com pé-direito alto, completa em armários, lazer com piscina e churrasqueira.",
    features: ["4 Suítes", "Piscina", "Armários Planejados", "Segurança 24h", "Garagem Ampla"],
    images: [
      "https://meridional.imb.br/resize.php?img=3317/2.jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3298",
    code: "ME-3298",
    title: "Residencial Torre Sul",
    type: "apartamento",
    category: "apartamento",
    purpose: "aluguel",
    price: 750000,
    rentalPrice: 5000,
    condoFee: 650,
    iptu: 950,
    neighborhood: "São Benedito",
    city: "Uberaba",
    state: "MG",
    address: "São Benedito",
    area: 140,
    builtArea: 140,
    bedrooms: 3,
    suites: 2,
    bathrooms: 4,
    parkingSpots: 2,
    featured: true,
    isSale: false,
    isRent: true,
    badge: "Locação Destaque",
    description: "Apartamento amplo no Residencial Torre Sul. 3 dormitórios (2 suítes), sala 2 ambientes com sacada gourmet, cozinha com armários e 2 vagas de garagem.",
    features: ["Sacada Gourmet", "2 Suítes", "Armários", "2 Vagas", "Prédio com Lazer"],
    images: [
      "https://meridional.imb.br/resize.php?img=3298/1(22).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3310",
    code: "ME-3310",
    title: "Casa São Benedito",
    type: "casa",
    category: "casa",
    purpose: "aluguel",
    price: 680000,
    rentalPrice: 3500,
    condoFee: 0,
    iptu: 850,
    neighborhood: "São Benedito",
    city: "Uberaba",
    state: "MG",
    address: "Bairro São Benedito",
    area: 260,
    builtArea: 200,
    bedrooms: 4,
    suites: 2,
    bathrooms: 5,
    parkingSpots: 2,
    featured: false,
    isSale: false,
    isRent: true,
    badge: "Locação Residencial",
    description: "Casa tradicional e espaçosa em localização privilegiada no São Benedito. 4 quartos (2 suítes), salas de estar e jantar, quintal e garagem para 2 carros.",
    features: ["4 Dormitórios", "Bairro Tradicional", "Quintal Espaçoso", "Garagem Coberta"],
    images: [
      "https://meridional.imb.br/resize.php?img=3310/capa.jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3307",
    code: "ME-3307",
    title: "Residencial Debran",
    type: "apartamento",
    category: "apartamento",
    purpose: "aluguel",
    price: 260000,
    rentalPrice: 1500,
    condoFee: 280,
    iptu: 450,
    neighborhood: "Mercês",
    city: "Uberaba",
    state: "MG",
    address: "Bairro Mercês",
    area: 75,
    builtArea: 75,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 1,
    featured: false,
    isSale: false,
    isRent: true,
    badge: "Excelente Custo",
    description: "Apartamento muito bem localizado no Mercês. 2 quartos sendo 1 suíte, sala, cozinha com armários e 1 vaga.",
    features: ["Mercês", "1 Suíte", "Cozinha com Armários", "Garagem"],
    images: [
      "https://meridional.imb.br/resize.php?img=3307/1(21).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3319",
    code: "ME-3319",
    title: "Edifício João Prata",
    type: "apartamento",
    category: "apartamento",
    purpose: "aluguel",
    price: 310000,
    rentalPrice: 1800,
    condoFee: 320,
    iptu: 500,
    neighborhood: "Centro",
    city: "Uberaba",
    state: "MG",
    address: "Região Central",
    area: 82,
    builtArea: 82,
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parkingSpots: 1,
    featured: false,
    isSale: false,
    isRent: true,
    badge: "Locação Centro",
    description: "Apartamento prático e bem localizado. 2 dormitórios sendo 1 suíte, sala com sacada, armários e elevador.",
    features: ["Centro", "Elevador", "Sacada", "Armários"],
    images: [
      "https://meridional.imb.br/resize.php?img=3319/1(5).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80"
    ]
  },

  // --- COMERCIAIS & GALPÕES ---
  {
    id: "3281",
    code: "ME-3281",
    title: "Galpão Comercial Univerdecidade",
    type: "comercial",
    category: "galpao",
    purpose: "aluguel",
    price: 6500000,
    rentalPrice: 40000,
    condoFee: 0,
    iptu: 3800,
    neighborhood: "Univerdecidade",
    city: "Uberaba",
    state: "MG",
    address: "Polo Logístico Univerdecidade",
    area: 2800,
    builtArea: 2200,
    bedrooms: 0,
    suites: 0,
    bathrooms: 6,
    parkingSpots: 12,
    featured: true,
    isSale: false,
    isRent: true,
    badge: "Polo Logístico",
    description: "Galpão industrial com pé direito de 10 metros, piso de alta resistência, 4 docas com nivelador e amplo pátio para manobra de carretas.",
    features: ["Pé-direito 10m", "4 Docas Niveladas", "Pátio de Manobras", "Fácil Acesso BR-050"],
    images: [
      "https://meridional.imb.br/resize.php?img=3281/1(3).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3083",
    code: "ME-3083",
    title: "Prédio Comercial Completo",
    type: "comercial",
    category: "comercial",
    purpose: "aluguel",
    price: 4200000,
    rentalPrice: 25000,
    condoFee: 0,
    iptu: 4500,
    neighborhood: "Centro",
    city: "Uberaba",
    state: "MG",
    address: "Centro de Uberaba",
    area: 950,
    builtArea: 850,
    bedrooms: 0,
    suites: 0,
    bathrooms: 5,
    parkingSpots: 5,
    featured: true,
    isSale: false,
    isRent: true,
    badge: "Prédio Corporativo",
    description: "Prédio comercial com 3 pavimentos livres, elevador, piso elevado, recepção climatizada e estacionamento frontal para clientes.",
    features: ["3 Pavimentos", "Elevador", "Estacionamento Privativo", "Piso Elevado"],
    images: [
      "https://meridional.imb.br/resize.php?img=3083/2(3).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3321",
    code: "ME-3321",
    title: "Casa Comercial no Centro",
    type: "comercial",
    category: "comercial",
    purpose: "aluguel",
    price: 1900000,
    rentalPrice: 10000,
    condoFee: 0,
    iptu: 2800,
    neighborhood: "Centro",
    city: "Uberaba",
    state: "MG",
    address: "Rua Vigário Silva, Centro",
    area: 480,
    builtArea: 400,
    bedrooms: 4,
    suites: 2,
    bathrooms: 4,
    parkingSpots: 4,
    featured: false,
    isSale: false,
    isRent: true,
    badge: "Clínicas & Escritórios",
    description: "Imóvel perfeito para clínicas médicas, escritórios ou sedes de empresas com excelente visibilidade no Centro de Uberaba.",
    features: ["Recepção Ampla", "Salas Climatizadas", "Estacionamento", "Centro Comercial"],
    images: [
      "https://meridional.imb.br/resize.php?img=3321/1(13).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80"
    ]
  },
  {
    id: "3261",
    code: "ME-3261",
    title: "Galpão Morumbi ME",
    type: "comercial",
    category: "galpao",
    purpose: "aluguel",
    price: 750000,
    rentalPrice: 4000,
    condoFee: 0,
    iptu: 650,
    neighborhood: "Morumbi",
    city: "Uberaba",
    state: "MG",
    address: "Bairro Morumbi",
    area: 450,
    builtArea: 380,
    bedrooms: 0,
    suites: 0,
    bathrooms: 2,
    parkingSpots: 4,
    featured: false,
    isSale: false,
    isRent: true,
    badge: "Galpão Morumbi",
    description: "Galpão comercial e de armazenagem com escritório, portão alto para caminhões e piso reforçado.",
    features: ["Piso Reforçado", "Portão Alto", "Escritório", "Fácil Acesso"],
    images: [
      "https://meridional.imb.br/resize.php?img=3261/1(9).jpeg&width=600&height=400",
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80"
    ]
  }
];

// --- LANÇAMENTOS COM BANNERS ORIGINAIS ---
const DEVELOPMENTS_DATA = [
  {
    id: "dev-turpan",
    code: "2916",
    title: "TURPAN - Residencial",
    badge: "Lançamento",
    type: "Apartamentos Modernos",
    status: "Em Construção",
    neighborhood: "Mercês",
    priceFrom: 289000,
    unitsDescription: "Unidades com varanda gourmet, plantas inteligentes e área de lazer com piscina.",
    banner: "https://meridional.imb.br/img_slyde.php?img=banners/slyde-1.jpg&width=1200&height=420",
    highlights: ["Varanda Gourmet", "Piscina", "Espaço Fitness", "Localização Privilegiada"]
  },
  {
    id: "dev-marialima",
    code: "3305",
    title: "Residencial Maria Lima",
    badge: "Destaque",
    type: "Casas em Condomínio Fechado",
    status: "Pronto para Morar",
    neighborhood: "Santa Marta",
    priceFrom: 460000,
    unitsDescription: "Casas térreas com 3 dormitórios (1 suíte) e segurança 24h.",
    banner: "https://meridional.imb.br/img_slyde.php?img=banners/slyde--293.jpg&width=1200&height=420",
    highlights: ["Portaria 24h", "Quintal Privativo", "Espaço Gourmet", "Baixo Condomínio"]
  },
  {
    id: "dev-jockey",
    code: "2972",
    title: "Residencial Jockey Ville",
    badge: "Loteamento Fechado",
    type: "Lotes & Casas Planejadas",
    status: "Últimas Unidades",
    neighborhood: "Jockey Park",
    priceFrom: 185000,
    unitsDescription: "Infraestrutura completa de lazer e segurança com parcelamento direto.",
    banner: "https://meridional.imb.br/img_slyde.php?img=banners/slyde--292.jpeg&width=1200&height=420",
    highlights: ["Financiamento Direto", "Pista de Caminhada", "Clube Completo", "Segurança"]
  },
  {
    id: "dev-barao",
    code: "2717",
    title: "Residencial Barão de Ituberaba",
    badge: "Alto Padrão",
    type: "Apartamentos Exclusivos",
    status: "Lançamento Nobre",
    neighborhood: "São Benedito",
    priceFrom: 1150000,
    unitsDescription: "1 por andar com 4 suítes, 3 vagas e vista panorâmica espetacular.",
    banner: "https://meridional.imb.br/img_slyde.php?img=banners/slyde--291.jpeg&width=1200&height=420",
    highlights: ["1 por Andar", "4 Suítes", "Elevador Privativo", "Piscina Aquecida"]
  },
  {
    id: "dev-ventuno",
    code: "2837",
    title: "VENTUNO - RESIDENCIAL",
    badge: "Lançamento",
    type: "Apartamentos Compactos & Modernos",
    status: "Obras Aceleradas",
    neighborhood: "Universitário",
    priceFrom: 230000,
    unitsDescription: "Ideal para morar ou investir na região universitária com alta liquidez.",
    banner: "https://meridional.imb.br/img_slyde.php?img=banners/slyde--288.jpeg&width=1200&height=420",
    highlights: ["Próximo a Faculdades", "Coworking", "Lavanderia Coletiva", "Academia"]
  },
  {
    id: "dev-villagavea",
    code: "2767",
    title: "Villa Gávea - Condomínio Brisas",
    badge: "Condomínio Fechado",
    type: "Casas Contemporâneas",
    status: "Fase de Lançamento",
    neighborhood: "Flamboyant",
    priceFrom: 690000,
    unitsDescription: "Casas em condomínio fechado com lazer completo estilo clube.",
    banner: "https://meridional.imb.br/img_slyde.php?img=banners/slyde--285.jpg&width=1200&height=420",
    highlights: ["Lazer de Clube", "3 Quartos", "Churrasqueira Privativa", "Playground"]
  },
  {
    id: "dev-aruna",
    code: "2680",
    title: "ARUNA RESIDENCIAL",
    badge: "Lançamento",
    type: "Apartamentos de 2 e 3 Quartos",
    status: "Breve Lançamento",
    neighborhood: "Mercês",
    priceFrom: 340000,
    unitsDescription: "Design arrojado, sustentabilidade e conforto no coração do Mercês.",
    banner: "https://meridional.imb.br/img_slyde.php?img=banners/slyde--272.jpeg&width=1200&height=420",
    highlights: ["Design Premiado", "Varanda Integrada", "Energia Solar", "Bairro Mercês"]
  }
];

const NEIGHBORHOODS_DATA = [
  { name: "Damha I, II e III", type: "Condomínios Fechados", listings: 48, tag: "Alto Padrão", desc: "Segurança armada 24h, lazer completo com lagos e máxima valorização." },
  { name: "Mercês", type: "Bairro Nobre & Tradicional", listings: 62, tag: "Mais Procurado", desc: "Sede da Meridional na Praça Dom Eduardo, próximo a clínicas e hospitais." },
  { name: "Flamboyant", type: "Condomínios & Residências", listings: 35, tag: "Familiar", desc: "Região residencial tranquila com condomínios fechados modernos." },
  { name: "Centro", type: "Comercial & Residencial", listings: 85, tag: "Conveniência", desc: "Acesso rápido a bancos, cartórios, colégios e comércio geral." },
  { name: "São Benedito", type: "Residencial & Gastronômico", listings: 41, tag: "Charme", desc: "Bairro tradicional arborizado com excelentes restaurantes e praças." },
  { name: "Univerdecidade", type: "Polo Logístico & Industrial", listings: 24, tag: "Empresarial", desc: "Grandes galpões e áreas logísticas com fácil acesso à BR-050." }
];

const BLOG_POSTS_DATA = [
  {
    id: "dica-1",
    title: "Como Financiar seu Imóvel pela Caixa em 2026: Guia Completo Passo a Passo",
    date: "18 Set 2026",
    category: "Financiamento",
    readTime: "4 min",
    summary: "Descubra como usar o FGTS, simular as melhores taxas de juros (SBPE e MCMV) e quais documentos são essenciais para aprovação rápida de crédito.",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "dica-2",
    title: "Por que Contratar um Perito Avaliador Judicial de Imóveis (CNAI)?",
    date: "12 Set 2026",
    category: "Perícia & Avaliação",
    readTime: "3 min",
    summary: "Entenda a importância do Parecer Técnico de Avaliação Mercadológica (PTAM) para inventários, partilhas e disputas judiciais com segurança jurídica.",
    image: "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "dica-3",
    title: "Mercado Imobiliário em Uberaba: Condomínios Fechados em Alta",
    date: "05 Set 2026",
    category: "Investimento",
    readTime: "5 min",
    summary: "Análise mercadológica sobre a valorização das regiões dos Damhas, Flamboyant e os novos eixos de crescimento da cidade.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"
  }
];

// Export to global scope
window.MERIDIONAL_DATA = {
  properties: PROPERTIES_DATA,
  developments: DEVELOPMENTS_DATA,
  neighborhoods: NEIGHBORHOODS_DATA,
  blogPosts: BLOG_POSTS_DATA,
  company: {
    name: "Imobiliária Meridional",
    legalName: "Meridional Corretores Associados",
    foundedYear: 1990,
    creci: "12.632 - 4ª Região / MG",
    founder: "Antonio Carlos Mendes (Técnico em Transações Imobiliárias & Perito Avaliador Judicial CNAI)",
    phone: "(34) 3312-6702",
    whatsapp: "(34) 9960-4600",
    whatsappClean: "553499604600",
    email: "meridionaluberaba@gmail.com",
    address: "Praça Dom Eduardo, 470 – Mercês, Uberaba – MG, CEP 38060-280",
    instagram: "https://www.instagram.com/meridionaluberaba/",
    facebook: "https://www.facebook.com/Meridional-178539326352585",
    caixaSimulatorUrl: "https://habitacao.caixa.gov.br/siopiweb-web/simulaOperacaoInternet.do?method=inicializarCasoUso"
  }
};
